# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: indigo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Optional

import betterproto


@dataclass
class InfluxTag(betterproto.Message):
    name: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)
    folder: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)


@dataclass
class InfluxEvent(betterproto.Message):
    measurement: Optional[str] = betterproto.message_field(
        1, wraps=betterproto.TYPE_STRING
    )
    time: Optional[str] = betterproto.message_field(2, wraps=betterproto.TYPE_STRING)
    tags: "InfluxTag" = betterproto.message_field(3)
    fields: "InfluxFields" = betterproto.message_field(4)


@dataclass
class DeviceChange(betterproto.Message):
    name: Optional[str] = betterproto.message_field(1, wraps=betterproto.TYPE_STRING)


@dataclass
class InfluxFields(betterproto.Message):
    on: Optional[bool] = betterproto.message_field(1, wraps=betterproto.TYPE_BOOL)
    cool_setpoint: Optional[float] = betterproto.message_field(
        3, wraps=betterproto.TYPE_FLOAT
    )
    heat_setpoint: Optional[float] = betterproto.message_field(
        4, wraps=betterproto.TYPE_FLOAT
    )
    temperature: Optional[float] = betterproto.message_field(
        5, wraps=betterproto.TYPE_FLOAT
    )
    humidity: Optional[float] = betterproto.message_field(
        6, wraps=betterproto.TYPE_FLOAT
    )
    brightness: Optional[float] = betterproto.message_field(
        11, wraps=betterproto.TYPE_FLOAT
    )
